# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_conspire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='comment',
        ),
    ]
