# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_conspire', '0002_remove_question_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asked_by', to='my_conspire.Answer'),
        ),
    ]
