# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_conspire', '0005_auto_20180809_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
