# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_conspire', '0006_article_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='feed',
            name='comment',
        ),
        migrations.AddField(
            model_name='feedcomment',
            name='feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_conspire.Feed'),
        ),
    ]
